/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.kth.iv1350.processSale.view;

import se.kth.iv1350.processSale.model.ReceiptObserver;
import java.text.DecimalFormat;

/**
 *  This class should display the totalRevenue generated by the Sale.
 * @author abdig
 */
public class TotalRevenueView extends RevenuePrinter {
    
    protected void printTotalRevenue(double totalRevenue)
    {
        System.out.println("TotalRevenueView: Chiching! Total revenue is now: " + df.format(totalRevenue));
    }
    
}
